### ISSUE TITLE
Mac Silicon builds

### ISSUE THREAD

**Issue by SidhNor** [maistra/istio-workspace#1032]
##### What can be improved

Is it possible to provide ARM builds for M1 macs?

##### Why

For all Mac M1 owners

**Comment by bartoszmajsak** [comment]
Hi @SidhNor! Thanks for your interest in the project. 

From the pure release point of view, it shouldn't be hard, especially since the tooling we use supports it. I need to look at the testing approach though, as we would like to avoid the situation of shipping sth which will only give you hard time using due to our limited testing resources (we don't have m1 silicons on our end...).

**Comment by bartoszmajsak** [comment]
@SidhNor We have released the `arm64` version as-is and will work on the testing side moving forward. Please report any issues you will find. Keeping our fingers crossed it actually works on your end :D
